// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileInfo():Promise<string>;

export function GetFileStr(arg1:number):Promise<Array<string>>;

export function Greet(arg1:string):Promise<Array<string>>;
