// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileInfo() {
  return window['go']['main']['App']['FileInfo']();
}

export function GetFileStr(arg1) {
  return window['go']['main']['App']['GetFileStr'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
